CREATE DATABASE IF NOT EXISTS retail_store;
USE retail_store;


CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    supplier_name TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,    
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT(11) NOT NULL DEFAULT 0,
    supplier_id INT(11),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sales (
    sale_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_id INT(11),
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    quantity_sold INT(11) NOT NULL,
    sale_date date NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);
